version: 1
updates:
  - package-ecosystem: "bundler"
    directory: "/"
    schedule:
      interval: "daily"
    open-pull-requests-limit: 0
    # Add/Remove reviewers here
    reviewers:
      - "JCarlosR"
